# Generated by Django 4.2.11 on 2026-02-16 16:48

from django.db import migrations, models


def seed_site_nav_text(apps, schema_editor):
    SiteNavText = apps.get_model("home", "SiteNavText")
    defaults = [
        {"key": "shop_all", "label_tr": "Tum Urunler", "label_en": "Shop All", "sort_order": 10, "is_active": True},
        {"key": "contact", "label_tr": "Iletisim", "label_en": "Contact", "sort_order": 20, "is_active": True},
        {"key": "about_us", "label_tr": "Hakkimizda", "label_en": "About Us", "sort_order": 30, "is_active": True},
        {"key": "more_info", "label_tr": "Daha Fazla Bilgi", "label_en": "More Info", "sort_order": 40, "is_active": True},
    ]
    for item in defaults:
        SiteNavText.objects.update_or_create(key=item["key"], defaults=item)


def remove_site_nav_text_seed(apps, schema_editor):
    SiteNavText = apps.get_model("home", "SiteNavText")
    SiteNavText.objects.filter(key__in=("shop_all", "contact", "about_us", "more_info")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x', 'X'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='Baglanti')),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='Etiket')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Siralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Linki',
                'verbose_name_plural': 'Sosyal Medya Linkleri',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteNavText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('shop_all', 'Shop All'), ('contact', 'Contact'), ('about_us', 'About Us'), ('more_info', 'More Info')], max_length=30, unique=True, verbose_name='Anahtar')),
                ('label_tr', models.CharField(max_length=120, verbose_name='Turkce Metin')),
                ('label_en', models.CharField(max_length=120, verbose_name='Ingilizce Metin')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Siralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Navbar ve Footer Metni',
                'verbose_name_plural': 'Navbar ve Footer Metinleri',
                'ordering': ('sort_order', 'key'),
            },
        ),
        migrations.RunPython(seed_site_nav_text, remove_site_nav_text_seed),
    ]
