# Generated by Django 4.2.11 on 2026-02-12 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate in decimal format, e.g. 0.20', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('priority', '-created_at'),
            },
        ),
    ]
