# Generated by Django 4.2.11 on 2026-02-11 12:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.01'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
