# Generated by Django 4.2.11 on 2026-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productvariant_cost_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
