# Generated by Django 4.2.11 on 2026-02-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productvariant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='TRY', max_length=10, verbose_name='Currency'),
        ),
    ]
