# Generated by Django 4.2.11 on 2026-02-11 14:38

from django.db import migrations


def force_try_currency(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    Product.objects.exclude(currency="TRY").update(currency="TRY")


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_currency'),
    ]

    operations = [
        migrations.RunPython(force_try_currency, migrations.RunPython.noop),
    ]
