# Generated by Django 4.2.11 on 2026-02-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('hidden', 'Hidden')], default='approved', max_length=20),
        ),
    ]
