# Generated by Django 4.2.11 on 2026-02-16 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productreview_report_count_productreview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Son Guncellenme Tarihi')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adi')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Siralama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Urun', 'verbose_name_plural': 'Urunler'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='TRY', max_length=10, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Yayinda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Guncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yayin Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subscribable',
            field=models.BooleanField(default=True, verbose_name='Abonelige Uygun'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SIMPLE_PRODUCT', 'Basit Urun'), ('GROUPED_PRODUCT', 'Hizmet'), ('EXTERNAL_PRODUCT', 'Harici/Ortaklik Urunu'), ('VARIABLE_PRODUCT', 'Varyantli Urun'), ('SIMPLE_SUBSCRIPTION', 'Basit Abonelik'), ('VARIABLE_SUBSCRIPTION', 'Varyantli Abonelik'), ('PRODUCT_BUNDLE', 'Urun Paketi')], default='SIMPLE_PRODUCT', max_length=25, verbose_name='Urun Turu'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Guncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandi'), ('hidden', 'Gizli')], default='approved', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.IntegerField(default=0, verbose_name='Dusuk Stok Esigi'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stok'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_status',
            field=models.CharField(choices=[('IN_STOCK', 'Stokta'), ('OUT_OF_STOCK', 'Stokta Yok')], default='IN_STOCK', max_length=15, verbose_name='Stok Durumu'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('GRAM', 'Gram'), ('KG', 'Kilogram'), ('LB', 'Libre'), ('OZ', 'Ons'), ('TON', 'Ton')], max_length=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='product_category_name_ci_unique'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='Kategori'),
        ),
    ]
