# Generated by Codex on 2026-02-16

import re

from django.db import migrations
from django.utils.text import slugify


def _normalize_text(value):
    return re.sub(r"\s+", " ", (value or "").strip())


def _unique_slug(base_text, used_slugs):
    base_slug = (slugify(base_text) or "kategori")[:100]
    candidate = base_slug
    counter = 2
    while candidate in used_slugs:
        suffix = f"-{counter}"
        candidate = f"{base_slug[: 120 - len(suffix)]}{suffix}"
        counter += 1
    used_slugs.add(candidate)
    return candidate


def _build_category_map(Category):
    category_map = {}
    used_slugs = set(Category.objects.values_list("slug", flat=True))

    for category in Category.objects.all().only("id", "name", "slug"):
        normalized_name = _normalize_text(category.name)
        if not normalized_name:
            continue
        category_map.setdefault(normalized_name.lower(), category)

    return category_map, used_slugs


def forwards(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    Category = apps.get_model("product", "Category")
    category_map, used_slugs = _build_category_map(Category)

    products = Product.objects.all().only("id", "category", "category_ref_id")
    for product in products.iterator():
        normalized_text = _normalize_text(product.category)
        if not normalized_text:
            continue

        key = normalized_text.lower()
        category = category_map.get(key)
        if not category:
            category = Category.objects.create(
                name=normalized_text,
                slug=_unique_slug(normalized_text, used_slugs),
                is_active=True,
                sort_order=0,
            )
            category_map[key] = category

        updates = {}
        if product.category != category.name:
            updates["category"] = category.name
        if product.category_ref_id != category.id:
            updates["category_ref_id"] = category.id
        if updates:
            Product.objects.filter(pk=product.pk).update(**updates)


def backwards(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    Category = apps.get_model("product", "Category")

    products = Product.objects.exclude(category_ref_id__isnull=True).only("id", "category", "category_ref_id")
    category_map = {str(c.id): c.name for c in Category.objects.all().only("id", "name")}
    for product in products.iterator():
        category_name = category_map.get(str(product.category_ref_id))
        if category_name and product.category != category_name:
            Product.objects.filter(pk=product.pk).update(category=category_name)


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_category_alter_product_options_alter_product_brand_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
