# Generated by Django 4.2.11 on 2026-02-12 08:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('paytr', 'PayTR'), ('manual', 'Manual')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('public_key', models.CharField(blank=True, default='', max_length=255)),
                ('secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=100)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='paytr', max_length=20)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('token', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TRY', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('request', 'Request'), ('callback', 'Callback'), ('webhook', 'Webhook')], max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payment.paymenttransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['idempotency_key'], name='payment_pay_idempot_e1693e_idx')],
            },
        ),
    ]
