# Generated by Django 4.2.11 on 2026-02-12 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('address_line1', models.CharField(max_length=180)),
                ('address_line2', models.CharField(blank=True, default='', max_length=180)),
                ('country', models.CharField(default='Turkiye', max_length=100)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default_shipping', '-created_at'),
                'indexes': [models.Index(fields=['user'], name='users_custo_user_id_f69748_idx'), models.Index(fields=['is_active'], name='users_custo_is_acti_4f9519_idx'), models.Index(fields=['city'], name='users_custo_city_a9c580_idx'), models.Index(fields=['district'], name='users_custo_distric_21894d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default_shipping', True)), fields=('user',), name='unique_default_shipping_address_per_user'),
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default_billing', True)), fields=('user',), name='unique_default_billing_address_per_user'),
        ),
    ]
