"""
Django settings for nxtbn project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

"""
 Important: Must Read this.
 01. The DEBUG and DEVELOPMENT_SERVER variables are not same thing. DEVELOPMENT_SERVER is custom for special purpose.
 02. Please read insturction of every enviroment variables to avoid any security risk
 03. To develop and solve a problem first, you first read whole settings.py files.
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from django.templatetags.static import static


load_dotenv()

import os

def get_env_var(key, default=None, var_type=str):
    value = os.getenv(key)
    if value is None:
        if default is not None:
            return default
        else:
            raise ValueError(f"Environment variable '{key}' is missing, and no default value is provided.")
    if var_type == int:
        return int(value)
    if var_type == bool:
        return value.lower() in ["true", "1", "yes"]
    if var_type == list:
        return [item.strip() for item in value.split(",") if item.strip()]
    return value


def static_or_fallback(path):
    """
    Return manifest-hashed static URL when available.
    Fall back to plain /static path to avoid 500 on missing manifest entries.
    """
    try:
        return static(path)
    except ValueError:
        return f"/static/{path.lstrip('/')}"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: Keep the secret key used in production confidential!
SECRET_KEY = get_env_var('SECRET_KEY')

# SECURITY WARNING: Debug mode exposes sensitive information and should only be used during development.
DEBUG = get_env_var("DEBUG", default=False, var_type=bool)
if os.getenv("DEBUG") is None and "runserver" in sys.argv:
    DEBUG = True
ENABLE_RATE_LIMITING = get_env_var("ENABLE_RATE_LIMITING", default=True, var_type=bool)

# SECURITY WARNING: Allowing all origins in production is a security risk.
CORS_ORIGIN_ALLOW_ALL = get_env_var("CORS_ORIGIN_ALLOW_ALL", default=False, var_type=bool)

ALLOWED_HOSTS = get_env_var("ALLOWED_HOSTS", default=["*"], var_type=list)

CORS_ALLOWED_ORIGINS = get_env_var("CORS_ALLOWED_ORIGINS", default=[
    'http://localhost:3000',
], var_type=list)
CSRF_TRUSTED_ORIGINS = get_env_var("CSRF_TRUSTED_ORIGINS", default=[], var_type=list)


DEVELOPMENT_SERVER = get_env_var("DEVELOPMENT_SERVER", default=False, var_type=bool)


SITE_ID = 1

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = get_env_var("SECURE_SSL_REDIRECT", default=False, var_type=bool)


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites'
]

LOCAL_APPS = [
    'nxtbn.core',
    'nxtbn.home',
    'nxtbn.checkout',
    'nxtbn.users.apps.UsersConfig',
    'nxtbn.dashboard_api',
    'nxtbn.storefront_api',
    'nxtbn.seo',
    'nxtbn.discount',
    'nxtbn.gift_card',
    'nxtbn.product',
    'nxtbn.invoice',
    'nxtbn.plugins',
    'nxtbn.payment',
    'nxtbn.order',
    'nxtbn.tax',
    'nxtbn.filemanager',
    'nxtbn.vendor',
]

HELPING_HAND_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'drf_yasg',
    'django_extensions',
    "corsheaders",
]

INSTALLED_APPS += LOCAL_APPS + HELPING_HAND_APPS

UNFOLD = {
    "SITE_TITLE": "Flexymedical Yonetim",
    "SITE_HEADER": "Flexymedical",
    "SITE_SUBHEADER": "Magaza yonetim merkezi",
    "SITE_LOGO": {
        "light": lambda request: static_or_fallback("images/logo.png"),
        "dark": lambda request: static_or_fallback("images/logo-full.png"),
    },
    "SITE_SYMBOL": None,
    "COLORS": {
        "primary": {
            "50": "#fff7ed",
            "100": "#ffedd5",
            "200": "#fed7aa",
            "300": "#fdba74",
            "400": "#fb923c",
            "500": "#f28c26",
            "600": "#d97310",
            "700": "#b45309",
            "800": "#92400e",
            "900": "#7c2d12",
            "950": "#431407",
        },
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_LANGUAGES": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Operasyon",
                "separator": True,
                "items": [
                    {
                        "title": "Operasyon Panosu",
                        "icon": "analytics",
                        "link": "/admin/operations/analytics/",
                    },
                    {
                        "title": "Siparisler",
                        "icon": "shopping_cart",
                        "link": "/admin/order/order/",
                    },
                    {
                        "title": "Urunler",
                        "icon": "inventory_2",
                        "link": "/admin/product/product/",
                    },
                    {
                        "title": "Odeme Islemleri",
                        "icon": "payments",
                        "link": "/admin/payment/paymenttransaction/",
                    },
                ],
            },
            {
                "title": "Musteri",
                "items": [
                    {
                        "title": "Kullanicilar",
                        "icon": "group",
                        "link": "/admin/users/user/",
                    },
                    {
                        "title": "Adresler",
                        "icon": "home_pin",
                        "link": "/admin/users/customeraddress/",
                    },
                ],
            },
            {
                "title": "Icerik ve Stok",
                "items": [
                    {
                        "title": "Dosya Yoneticisi",
                        "icon": "folder",
                        "link": "/admin/filemanager/image/",
                    },
                    {
                        "title": "Kampanyalar",
                        "icon": "sell",
                        "link": "/admin/discount/coupon/",
                    },
                    {
                        "title": "Vergi Kurallari",
                        "icon": "receipt_long",
                        "link": "/admin/tax/taxrule/",
                    },
                    {
                        "title": "Anasayfa Slayt",
                        "icon": "view_carousel",
                        "link": "/admin/home/homeslide/",
                    },
                    {
                        "title": "Tedarikciler",
                        "icon": "local_shipping",
                        "link": "/admin/vendor/vendor/",
                    },
                ],
            },
            {
                "title": "Site Icerigi",
                "items": [
                    {
                        "title": "Navbar ve Footer Metinleri",
                        "icon": "menu_book",
                        "link": "/admin/home/sitenavtext/",
                    },
                    {
                        "title": "Sosyal Medya Linkleri",
                        "icon": "share",
                        "link": "/admin/home/footersociallink/",
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'nxtbn.core.middleware.SecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

if ENABLE_RATE_LIMITING:
    MIDDLEWARE.insert(8, 'nxtbn.core.middleware.RateLimitMiddleware')

ROOT_URLCONF = 'nxtbn.urls'


DEFAULT_TEMPLATE_ID = get_env_var('DEFAULT_TEMPLATE_ID', 'templates')
DEFAULT_TEMPLATE_PATH = DEFAULT_TEMPLATE_ID + '/templates' if DEFAULT_TEMPLATE_ID.startswith('3rd') else  DEFAULT_TEMPLATE_ID

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, DEFAULT_TEMPLATE_PATH)],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nxtbn.home.context_processors.storefront_navigation_content',
            ],
        },
    },
]

WSGI_APPLICATION = 'nxtbn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if get_env_var('DATABASE_NAME', ''):
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_var('DATABASE_NAME', ''),
        'USER': get_env_var('DATABASE_USER', ''),
        'PASSWORD': get_env_var('DATABASE_PASSWORD', ''),
        'HOST': get_env_var('DATABASE_HOST', ''),
        'PORT': get_env_var('DATABASE_PORT', ''),
        }
    }
else:
   DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# When test, use sqlute as test DB
if len(sys.argv) > 1 and sys.argv[1] == 'test':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'tr'

LANGUAGES = [
    ("tr", "Turkish"),
    ("en", "English"),
]

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if DEFAULT_TEMPLATE_ID.startswith('3rd'):
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]
else:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]

MEDIA_URL = get_env_var("MEDIA_URL", default='/media/')
MEDIA_ROOT = get_env_var("MEDIA_ROOT", default=os.path.join(BASE_DIR, 'media'))
SERVE_MEDIA = get_env_var("SERVE_MEDIA", default=False, var_type=bool)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# more details can be found here http://whitenoise.evans.io/en/stable/
# Use non-manifest storage during development so admin CSS updates are visible immediately.
if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# More details can be found here: https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
AWS_ACCESS_KEY_ID = get_env_var("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = get_env_var("AWS_SECRET_ACCESS_KEY", "")
AWS_STORAGE_BUCKET_NAME = get_env_var("AWS_STORAGE_BUCKET_NAME", "")
AWS_STORAGE_REGION = get_env_var("AWS_STORAGE_REGION", "")

IS_AWS_S3 = (
    AWS_ACCESS_KEY_ID and
    AWS_SECRET_ACCESS_KEY and
    AWS_STORAGE_BUCKET_NAME and
    AWS_STORAGE_REGION
)

if IS_AWS_S3:
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_CUSTOM_DOMAIN = get_env_var("AWS_S3_CUSTOM_DOMAIN", "")
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    AWS_DEFAULT_ACL = get_env_var("AWS_DEFAULT_ACL", "public-read")
    AWS_LOCATION = "media"
    AWS_AUTO_CREATE_BUCKET = get_env_var("AWS_AUTO_CREATE_BUCKET", True, var_type=bool)
    DEFAULT_FILE_STORAGE = get_env_var(
        "DEFAULT_FILE_STORAGE", "nxtbn.users.storages.NxtbnS3Storage"
    )


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauth config
ACCOUNT_EMAIL_VERIFICATION =  get_env_var("ACCOUNT_EMAIL_VERIFICATION", "optional")
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_UNIQUE_EMAIL = True
LOGIN_REDIRECT_URL = "account_profiles"

ACCOUNT_ADAPTER = "nxtbn.users.auth_adapters.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "nxtbn.users.auth_adapters.CustomSocialAccountAdapter"

ACCOUNT_FORMS = { # Allauth Server-side signup rendered signup
    'signup': 'nxtbn.users.forms.AllauthSignupForm',
}


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication', # https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
}

if DEVELOPMENT_SERVER:
    REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'].append(
        'nxtbn.users.authentication.CsrfExemptSessionAuthentication' # WARNING: Not Secure
    )


AUTH_USER_MODEL = "users.User" 
  
EMAIL_HOST = get_env_var("EMAIL_HOST", "")
EMAIL_HOST_USER =get_env_var("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = get_env_var("EMAIL_HOST_PASSWORD", "")
EMAIL_PORT =  get_env_var("EMAIL_PORT", '')
EMAIL_USE_TLS = get_env_var("EMAIL_USE_TLS", False, var_type=bool)
DEFAULT_FROM_EMAIL = get_env_var("DEFAULT_FROM_EMAIL", "")

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

IS_SMTP = (
    EMAIL_HOST and EMAIL_PORT
)

if IS_SMTP:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "nxtbn-default-cache",
    }
}

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = get_env_var("SECURE_HSTS_SECONDS", default=0 if DEBUG else 31536000, var_type=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_env_var("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG, var_type=bool)
SECURE_HSTS_PRELOAD = get_env_var("SECURE_HSTS_PRELOAD", default=not DEBUG, var_type=bool)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}



SWAGGER_SETTINGS = { # "Token <YOUR TOKEN>""
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization' # 'rest_framework.authentication.TokenAuthentication',
        }
    },
}


THIRD_PARTY_PLUGGINS = get_env_var("THIRD_PARTY_PLUGGINS", default=[], var_type=list)

INSTALLED_PLUGINS = [
    # 'pluggins.payment.stripe'
]

INSTALLED_PLUGINS += INSTALLED_PLUGINS + THIRD_PARTY_PLUGGINS
